name: Deploy React to EC2

on:
  push:
    branches:
      - master  # Deploy when code is pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug
      run: ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Create .env file  # Step to inject the REACT_APP_BACKEND_URL
      run: |
        echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" > .env

    - name: Install dependencies
      run: npm install

    - name: Build React application
      run: |
        npm run build  # Creates a production build in 'build/' with env variables embedded

    - name: Deploy build folder to EC2 via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        source: "build/*"
        target: "/var/www/html/crm-frontend"

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: sudo systemctl restart nginx
